<header class="main-header">
    <i class="fal fa-bars"></i>
    <h1 class="logo">SAVE <i class="fas fa-star-of-life"></i><strong class="logo-strong"> DEMIC</strong></h1>
    <i class="fas fa-exclamation-triangle warning"></i>
</header>
<section class="main-content">
    <section class="content-header">
        <p class="verbo-encher"></p>
            <p class="content-header-text">

                <p>COVID-19</p>
                <i class="fal fa-biohazard content-header-virus"></i>
            </p>
        <div class="stats">

        </div>
    </section>



    <article class="trending">
        <section class="article-section on-the-rise">
            <header class="on-the-rise-header">
                <p>Em Alta</p>
            </header>
            <p class="on-the-rise-content-desc">
                <i class="fal fa-biohazard on-the-rise-type"></i>
                <p class="on-the-rise-text">
                    CoronaVirus
                </p>
            </p>
            <p class="on-the-rise-text">
                <a href="">Read More</a>
            </p>
        </section> 
        <section class="article-section on-the-rise">
            <header class="on-the-rise-header">
                <p>Prevenção</p>
            </header>
                <p class="on-the-rise-content-desc">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                </p>
                <p class="on-the-rise-text">
                    <a href="">Read More</a>
                </p>
        </section> 
        <section class="article-section on-the-rise">
            <header class="on-the-rise-header">
                <p>Estado</p>
            </header>
                <p class="on-the-rise-content-desc">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                </p>
                <p class="on-the-rise-text">
                    <a href="">Read More</a>
                </p>
        </section> 
        <section class="article-section on-the-rise">
            <header class="on-the-rise-header">
                <p>Tratamento</p>
            </header>
                <p class="on-the-rise-content-desc">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                </p>
                <p class="on-the-rise-text">
                    <a href="">Read More</a>
                </p>
        </section> 
    </article>
</section>
    <section class="news-section">
    <article class="news-section-each">
            <p class="news-title">
                Notícia COVID-19
            </p>
            <p class="news-descryption">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id vitae, ex error praesentium eveniet atque, quasi quas tempora, aliquam iusto unde ut voluptas beatae? Nam numquam pariatur tenetur tempore ad!
            </p>
        </article>
        <article class="news-section-each">
            <p class="news-title">
                Notícia COVID-19
            </p>
            <p class="news-descryption">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id vitae, ex error praesentium eveniet atque, quasi quas tempora, aliquam iusto unde ut voluptas beatae? Nam numquam pariatur tenetur tempore ad!
            </p>
        </article>
        <article class="news-section-each">
            <p class="news-title">
                Notícia COVID-19
            </p>
            <p class="news-descryption">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id vitae, ex error praesentium eveniet atque, quasi quas tempora, aliquam iusto unde ut voluptas beatae? Nam numquam pariatur tenetur tempore ad!
            </p>
        </article>
    </section>
